DX = 60.0
DY = 60.0
DZ = 60.0  

Z_UP   = 100.0
X_PULL = -100.0

INSPECT_TIME = 4.0   # 3~5s 느낌(대표값)

V_FAST = 70
A_FAST = 70
V_SLOW = 30
A_SLOW = 30

HOME_P = posx(367.22, 3.83, 201.28, 158.41, 179.96, 158.79)

S1_BASE = (750.39,  200.46, 250.92,   2.36,   88.13,   2.04)
S2_BASE = (429.80, -258.59,  86.78, 115.36, -179.93, 116.26)
S3_BASE = (429.06,  213.83,  87.04, 154.82,  179.97, 155.23)

S1_AXIS = 'z'
S2_AXIS = 'x'
S3_AXIS = 'x'

def open_gripper():
    set_digital_output(1, OFF); set_digital_output(2, ON)

def close_gripper():
    set_digital_output(1, ON); set_digital_output(2, OFF)

def do_homing():
    pass


def slot_pose(base, i, axis):
    x0, y0, z0, A0, B0, C0 = base

    x = x0
    y = y0
    z = z0

    if axis == 'x':
        x = x0 + i * DX
    elif axis == 'y':
        y = y0 + i * DY
    elif axis == 'z':
        z = z0 + i * DZ

    return posx(x, y, z, A0, B0, C0)


def app_pose_zup(base, i, axis):
    x0, y0, z0, A0, B0, C0 = base

    x = x0
    y = y0
    z = z0

    if axis == 'x':
        x = x0 + i * DX
    elif axis == 'y':
        y = y0 + i * DY
    elif axis == 'z':
        z = z0 + i * DZ

    return posx(x, y, z + Z_UP, A0, B0, C0)


def app_pose_xpull(base, i, axis, x_pull):
    x0, y0, z0, A0, B0, C0 = base

    x = x0
    y = y0
    z = z0

    if axis == 'x':
        x = x0 + i * DX
    elif axis == 'y':
        y = y0 + i * DY
    elif axis == 'z':
        z = z0 + i * DZ

    return posx(x + x_pull, y, z, A0, B0, C0)


def go_home():
    movel(HOME_P, v=V_FAST, a=A_FAST)


def go_slot_zup(base, i, axis):
    p_app  = app_pose_zup(base, i, axis)
    p_work = slot_pose(base, i, axis)
    movel(p_app,  v=V_FAST, a=A_FAST)
    movel(p_work, v=V_SLOW, a=A_SLOW)


def leave_slot_zup(base, i, axis):
    p_app = app_pose_zup(base, i, axis)
    movel(p_app, v=V_FAST, a=A_FAST)


def go_slot_xpull(base, i, axis, x_pull):
    p_app  = app_pose_xpull(base, i, axis, x_pull)
    p_work = slot_pose(base, i, axis)
    movel(p_app,  v=V_FAST, a=A_FAST)
    movel(p_work, v=V_SLOW, a=A_SLOW)


def leave_slot_xpull(base, i, axis, x_pull):
    p_app = app_pose_xpull(base, i, axis, x_pull)
    movel(p_app, v=V_FAST, a=A_FAST)


def pick_from_shelf1(base, i, axis, x_pull):
    open_gripper()
    wait(0.2)

    go_slot_xpull(base, i, axis, x_pull)

    close_gripper()
    wait(0.3)

    leave_slot_xpull(base, i, axis, x_pull)


def place_to_shelf3(base, i, axis):
    go_slot_zup(base, i, axis)

    open_gripper()
    wait(0.3)

    leave_slot_zup(base, i, axis)


def main():
    s1_idx = 0
    s2_idx = 0
    s3_idx = 0

    go_home()

    pick_from_shelf1(S1_BASE, s1_idx, S1_AXIS, X_PULL)
    go_home()

    go_slot_zup(S2_BASE, s2_idx, S2_AXIS)
    wait(INSPECT_TIME)
    leave_slot_zup(S2_BASE, s2_idx, S2_AXIS)

    place_to_shelf3(S3_BASE, s3_idx, S3_AXIS)
    go_home()

    do_homing()
    go_home()


main()
